/**
 * Admin erőforrás-definíciók: egy generikus tábla+űrlap komponens ezekből
 * építi a listát és a szerkesztőt. Új tábla admin felülete = új bejegyzés itt.
 */
export type FieldType = "text" | "textarea" | "number" | "boolean" | "select" | "json" | "color" | "file" | "readonly";

export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  /** fix opciók (enumok) */
  options?: { value: string; label: string }[];
  /** FK opciók másik táblából */
  ref?: { table: string; labelKey: string; valueKey?: string };
  /** file típusnál: bucket és mappa */
  bucket?: string;
  folder?: string;
  help?: string;
}

export interface ResourceDef {
  key: string;
  table: string;
  title: string;
  description: string;
  idKey: string;
  listColumns: string[];
  fields: FieldDef[];
  orderBy?: { column: string; ascending?: boolean };
  canCreate?: boolean;
  canDelete?: boolean;
  group: "Katalógus" | "Testreszabás" | "Tartalom" | "Vásárlók" | "Beállítások";
}

const ORDER_STATUS = ["pending", "confirmed", "in_production", "ready", "shipped", "delivered", "cancelled", "refunded"].map((v) => ({ value: v, label: v }));
const PAYMENT_STATUS = ["unpaid", "pending", "paid", "refunded", "failed"].map((v) => ({ value: v, label: v }));
const APPLICATION_STATUS = ["submitted", "reviewing", "approved", "rejected", "fulfilled"].map((v) => ({ value: v, label: v }));
const GENDER = ["women", "men", "unisex"].map((v) => ({ value: v, label: v }));
const VIEWS = ["front", "back", "left_sleeve", "right_sleeve"].map((v) => ({ value: v, label: v }));
const SILHOUETTES = ["tshirt", "hoodie", "sweatshirt", "tank", "shorts", "pants", "dress", "skirt"].map((v) => ({ value: v, label: v }));

export const ADMIN_RESOURCES: ResourceDef[] = [
  {
    key: "categories",
    table: "categories",
    title: "Kategóriák",
    description: "Terméktípusok – új kategória kódmódosítás nélkül.",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["slug", "name", "silhouette", "sort_order", "is_active"],
    orderBy: { column: "sort_order" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "description", label: "Leírás", type: "textarea" },
      { key: "silhouette", label: "Sziluett", type: "select", options: SILHOUETTES },
      { key: "image_path", label: "Kép", type: "file", bucket: "product-images", folder: "categories" },
      { key: "sort_order", label: "Sorrend", type: "number" },
      { key: "is_active", label: "Aktív", type: "boolean" },
    ],
  },
  {
    key: "products",
    table: "products",
    title: "Termékek",
    description: "Ruhák: kategória, nem, 3D modell, mérettáblázat, ár.",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["slug", "name", "gender", "base_price_huf", "is_active", "is_featured"],
    orderBy: { column: "sort_order" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "description", label: "Leírás", type: "textarea" },
      { key: "category_id", label: "Kategória", type: "select", ref: { table: "categories", labelKey: "name" }, required: true },
      { key: "gender", label: "Nem", type: "select", options: GENDER },
      { key: "garment_model_id", label: "3D/2D modell", type: "select", ref: { table: "garment_models", labelKey: "name" } },
      { key: "size_chart_id", label: "Mérettáblázat", type: "select", ref: { table: "size_charts", labelKey: "name" } },
      { key: "silhouette", label: "Sziluett", type: "select", options: SILHOUETTES },
      { key: "base_price_huf", label: "Alapár (Ft)", type: "number", required: true },
      { key: "is_active", label: "Aktív", type: "boolean" },
      { key: "is_featured", label: "Kiemelt", type: "boolean" },
      { key: "is_customizable", label: "Testreszabható", type: "boolean" },
      { key: "tags", label: "Címkék (JSON tömb)", type: "json" },
      { key: "sort_order", label: "Sorrend", type: "number" },
    ],
  },
  {
    key: "product_variants",
    table: "product_variants",
    title: "Termékvariánsok",
    description: "Fazon × szín × méret, készlet, ár-felülírás.",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["sku", "stock_qty", "price_override_huf", "is_active"],
    orderBy: { column: "sku" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "product_id", label: "Termék", type: "select", ref: { table: "products", labelKey: "name" }, required: true },
      { key: "sku", label: "SKU", type: "text", required: true },
      { key: "fit_id", label: "Fazon", type: "select", ref: { table: "fits", labelKey: "name" }, required: true },
      { key: "color_id", label: "Szín", type: "select", ref: { table: "colors", labelKey: "name" }, required: true },
      { key: "size_id", label: "Méret", type: "select", ref: { table: "sizes", labelKey: "code" }, required: true },
      { key: "price_override_huf", label: "Ár felülírás (Ft)", type: "number" },
      { key: "stock_qty", label: "Készlet", type: "number" },
      { key: "is_active", label: "Aktív", type: "boolean" },
    ],
  },
  {
    key: "product_images",
    table: "product_images",
    title: "Termékképek",
    description: "Galéria és sablonképek termékenként, opcionálisan színhez kötve.",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["storage_path", "kind", "sort_order"],
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "product_id", label: "Termék", type: "select", ref: { table: "products", labelKey: "name" }, required: true },
      { key: "color_id", label: "Szín", type: "select", ref: { table: "colors", labelKey: "name" } },
      { key: "storage_path", label: "Kép", type: "file", bucket: "product-images", folder: "products", required: true },
      { key: "alt", label: "Alt szöveg", type: "text" },
      { key: "kind", label: "Típus", type: "select", options: ["gallery", "thumbnail", "template_front", "template_back"].map((v) => ({ value: v, label: v })) },
      { key: "sort_order", label: "Sorrend", type: "number" },
    ],
  },
  {
    key: "fits",
    table: "fits",
    title: "Fazonok",
    description: "Regular, slim, oversized…",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["slug", "name", "sort_order", "is_active"],
    orderBy: { column: "sort_order" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "description", label: "Leírás", type: "textarea" },
      { key: "sort_order", label: "Sorrend", type: "number" },
      { key: "is_active", label: "Aktív", type: "boolean" },
    ],
  },
  {
    key: "colors",
    table: "colors",
    title: "Színek",
    description: "Ruhaszínek hex kóddal.",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["slug", "name", "hex", "is_active"],
    orderBy: { column: "sort_order" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "hex", label: "Hex", type: "color", required: true },
      { key: "sort_order", label: "Sorrend", type: "number" },
      { key: "is_active", label: "Aktív", type: "boolean" },
    ],
  },
  {
    key: "sizes",
    table: "sizes",
    title: "Méretek",
    description: "XS–XXL és egyéb méretkódok.",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["code", "name", "sort_order", "is_active"],
    orderBy: { column: "sort_order" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "code", label: "Kód", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "sort_order", label: "Sorrend", type: "number" },
      { key: "is_active", label: "Aktív", type: "boolean" },
    ],
  },
  {
    key: "size_charts",
    table: "size_charts",
    title: "Mérettáblázatok",
    description: "Termékenként külön táblázat; measurement_keys: chest, length, shoulder, sleeve, waist, hip.",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["slug", "name", "measurement_keys"],
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "measurement_keys", label: "Mezők (JSON tömb)", type: "json", help: '["chest","length","shoulder","sleeve"]' },
    ],
  },
  {
    key: "size_chart_entries",
    table: "size_chart_entries",
    title: "Mérettáblázat sorok",
    description: "Méretenként cm értékek: {\"chest\":100,\"length\":70}",
    idKey: "id",
    group: "Katalógus",
    listColumns: ["measurements"],
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "size_chart_id", label: "Táblázat", type: "select", ref: { table: "size_charts", labelKey: "name" }, required: true },
      { key: "size_id", label: "Méret", type: "select", ref: { table: "sizes", labelKey: "code" }, required: true },
      { key: "measurements", label: "Értékek (JSON)", type: "json", required: true },
    ],
  },
  {
    key: "garment_models",
    table: "garment_models",
    title: "3D ruhamodellek",
    description: "GLB modellek, cm-kalibrált chartok és szerkesztő nézetek (JSON).",
    idKey: "id",
    group: "Testreszabás",
    listColumns: ["slug", "name", "model_path", "mapping_mode", "is_active"],
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "model_path", label: "GLB modell", type: "file", bucket: "garment-models", folder: "models", help: "Blenderből exportált GLB; a chartok cm-kalibráltak legyenek (docs/3D-CUSTOMIZER.md)." },
      { key: "preview_image_path", label: "Előnézeti kép", type: "file", bucket: "garment-models", folder: "previews" },
      { key: "mapping_mode", label: "Leképezés", type: "select", options: [{ value: "uv", label: "uv (textúra)" }, { value: "decal", label: "decal" }] },
      { key: "silhouette", label: "Sziluett", type: "select", options: SILHOUETTES },
      { key: "charts", label: "Chartok (JSON)", type: "json", help: '[{"key":"torso","meshName":"Torso","widthCm":108,"heightCm":72}]' },
      { key: "views", label: "Nézetek (JSON)", type: "json" },
      { key: "is_active", label: "Aktív", type: "boolean" },
    ],
  },
  {
    key: "customization_zones",
    table: "customization_zones",
    title: "Hímzési zónák",
    description: "Zónák modellenként: cm bounding box, min/max méret, nézet.",
    idKey: "id",
    group: "Testreszabás",
    listColumns: ["key", "display_name", "view_key", "rect_w", "rect_h", "max_width_cm", "max_height_cm", "is_active"],
    orderBy: { column: "sort_order" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "garment_model_id", label: "Modell", type: "select", ref: { table: "garment_models", labelKey: "name" }, required: true },
      { key: "key", label: "Kulcs", type: "text", required: true, help: "pl. front_center" },
      { key: "display_name", label: "Megjelenített név", type: "text", required: true },
      { key: "view_key", label: "Nézet", type: "select", options: VIEWS },
      { key: "rect_x", label: "X (cm)", type: "number", required: true },
      { key: "rect_y", label: "Y (cm)", type: "number", required: true },
      { key: "rect_w", label: "Szélesség (cm)", type: "number", required: true },
      { key: "rect_h", label: "Magasság (cm)", type: "number", required: true },
      { key: "min_width_cm", label: "Min. szélesség (cm)", type: "number" },
      { key: "max_width_cm", label: "Max. szélesség (cm)", type: "number", required: true },
      { key: "max_height_cm", label: "Max. magasság (cm)", type: "number", required: true },
      { key: "mapping_3d", label: "3D mapping (JSON, decal módhoz)", type: "json" },
      { key: "is_active", label: "Aktív", type: "boolean" },
      { key: "sort_order", label: "Sorrend", type: "number" },
    ],
  },
  {
    key: "design_assets",
    table: "design_assets",
    title: "Design assetek",
    description: "Beépített minták a Studióhoz (design-assets bucket).",
    idKey: "id",
    group: "Testreszabás",
    listColumns: ["slug", "name", "storage_path", "is_active"],
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true },
      { key: "name", label: "Név", type: "text", required: true },
      { key: "storage_path", label: "Fájl (SVG/PNG)", type: "file", bucket: "design-assets", folder: "library", required: true },
      { key: "tags", label: "Címkék (JSON tömb)", type: "json" },
      { key: "is_active", label: "Aktív", type: "boolean" },
      { key: "sort_order", label: "Sorrend", type: "number" },
    ],
  },
  {
    key: "user_uploads",
    table: "user_uploads",
    title: "Felhasználói feltöltések",
    description: "Csak olvasás: a vásárlók által feltöltött forrásfájlok.",
    idKey: "id",
    group: "Testreszabás",
    listColumns: ["original_filename", "mime_type", "width_px", "height_px", "is_vector", "created_at"],
    orderBy: { column: "created_at", ascending: false },
    fields: [
      { key: "user_id", label: "Felhasználó", type: "readonly" },
      { key: "storage_path", label: "Storage út", type: "readonly" },
      { key: "preview_path", label: "Előnézet út", type: "readonly" },
      { key: "original_filename", label: "Fájlnév", type: "readonly" },
      { key: "mime_type", label: "MIME", type: "readonly" },
      { key: "sanitized", label: "Tisztított", type: "boolean" },
    ],
  },
  {
    key: "gallery_items",
    table: "gallery_items",
    title: "Galéria",
    description: "Inspirációs galéria elemei.",
    idKey: "id",
    group: "Tartalom",
    listColumns: ["title", "zone_key", "likes_count", "is_published", "sort_order"],
    orderBy: { column: "sort_order" },
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "title", label: "Cím", type: "text", required: true },
      { key: "description", label: "Leírás", type: "textarea" },
      { key: "image_path", label: "Kép", type: "file", bucket: "product-images", folder: "gallery" },
      { key: "product_id", label: "Termék", type: "select", ref: { table: "products", labelKey: "name" } },
      { key: "color_id", label: "Szín", type: "select", ref: { table: "colors", labelKey: "name" } },
      { key: "design_asset_id", label: "Design asset", type: "select", ref: { table: "design_assets", labelKey: "name" } },
      { key: "zone_key", label: "Zóna", type: "text" },
      { key: "width_cm", label: "Szélesség (cm)", type: "number" },
      { key: "height_cm", label: "Magasság (cm)", type: "number" },
      { key: "tags", label: "Címkék (JSON tömb)", type: "json" },
      { key: "likes_count", label: "Like", type: "number" },
      { key: "is_published", label: "Publikált", type: "boolean" },
      { key: "sort_order", label: "Sorrend", type: "number" },
    ],
  },
  {
    key: "creator_applications",
    table: "creator_applications",
    title: "Creator jelentkezések",
    description: "Manuális elbírálás: submitted → reviewing → approved/rejected → fulfilled.",
    idKey: "id",
    group: "Vásárlók",
    listColumns: ["name", "platform", "social_username", "follower_count", "status", "created_at"],
    orderBy: { column: "created_at", ascending: false },
    canDelete: true,
    fields: [
      { key: "name", label: "Név", type: "readonly" },
      { key: "email", label: "E-mail", type: "readonly" },
      { key: "platform", label: "Platform", type: "readonly" },
      { key: "social_username", label: "Felhasználónév", type: "readonly" },
      { key: "profile_url", label: "Profil URL", type: "readonly" },
      { key: "follower_count", label: "Követők", type: "readonly" },
      { key: "content_idea", label: "Tartalomötlet", type: "readonly" },
      { key: "post_plan", label: "Poszt terv", type: "readonly" },
      { key: "screenshot_path", label: "Képernyőkép (creator-applications bucket)", type: "readonly" },
      { key: "notes", label: "Megjegyzés", type: "readonly" },
      { key: "status", label: "Státusz", type: "select", options: APPLICATION_STATUS },
      { key: "admin_notes", label: "Admin megjegyzés", type: "textarea" },
    ],
  },
  {
    key: "profiles",
    table: "profiles",
    title: "Felhasználók",
    description: "Profilok és szerepkörök.",
    idKey: "id",
    group: "Vásárlók",
    listColumns: ["email", "display_name", "role", "created_at"],
    orderBy: { column: "created_at", ascending: false },
    fields: [
      { key: "email", label: "E-mail", type: "readonly" },
      { key: "display_name", label: "Név", type: "text" },
      { key: "phone", label: "Telefon", type: "text" },
      { key: "role", label: "Szerep", type: "select", options: [{ value: "customer", label: "customer" }, { value: "admin", label: "admin" }] },
    ],
  },
  {
    key: "orders",
    table: "orders",
    title: "Rendelések",
    description: "Státusz, fizetés, megjegyzések. A státuszváltás naplózódik.",
    idKey: "id",
    group: "Vásárlók",
    listColumns: ["order_number", "customer_name", "status", "payment_status", "total_huf", "placed_at"],
    orderBy: { column: "placed_at", ascending: false },
    fields: [
      { key: "order_number", label: "Rendelésszám", type: "readonly" },
      { key: "customer_name", label: "Név", type: "readonly" },
      { key: "email", label: "E-mail", type: "readonly" },
      { key: "phone", label: "Telefon", type: "readonly" },
      { key: "shipping_address", label: "Szállítási cím", type: "json" },
      { key: "shipping_method", label: "Szállítás", type: "text" },
      { key: "shipping_reference", label: "Csomagkövetés", type: "text" },
      { key: "payment_method", label: "Fizetés", type: "readonly" },
      { key: "payment_status", label: "Fizetési státusz", type: "select", options: PAYMENT_STATUS },
      { key: "status", label: "Rendelési státusz", type: "select", options: ORDER_STATUS },
      { key: "total_huf", label: "Összesen (Ft)", type: "readonly" },
      { key: "notes", label: "Vásárlói megjegyzés", type: "readonly" },
      { key: "admin_notes", label: "Admin megjegyzés", type: "textarea" },
    ],
  },
  {
    key: "order_items",
    table: "order_items",
    title: "Rendelési tételek",
    description: "Csak olvasás: tételek design-snapshottal (gyártáshoz).",
    idKey: "id",
    group: "Vásárlók",
    listColumns: ["product_name", "quantity", "unit_price_huf", "line_total_huf"],
    fields: [
      { key: "product_name", label: "Termék", type: "readonly" },
      { key: "variant_snapshot", label: "Variáns", type: "readonly" },
      { key: "design_snapshot", label: "Design snapshot", type: "readonly" },
      { key: "quantity", label: "Db", type: "readonly" },
    ],
  },
  {
    key: "contact_messages",
    table: "contact_messages",
    title: "Kapcsolati üzenetek",
    description: "Beérkezett üzenetek.",
    idKey: "id",
    group: "Vásárlók",
    listColumns: ["name", "email", "subject", "status", "created_at"],
    orderBy: { column: "created_at", ascending: false },
    canDelete: true,
    fields: [
      { key: "name", label: "Név", type: "readonly" },
      { key: "email", label: "E-mail", type: "readonly" },
      { key: "subject", label: "Tárgy", type: "readonly" },
      { key: "message", label: "Üzenet", type: "readonly" },
      { key: "status", label: "Státusz", type: "select", options: ["new", "answered", "archived"].map((v) => ({ value: v, label: v })) },
    ],
  },
  {
    key: "site_settings",
    table: "site_settings",
    title: "Oldalbeállítások",
    description: "Kontakt, hero, featured, creator szabályok, pricing – JSON értékek kulcsonként.",
    idKey: "key",
    group: "Beállítások",
    listColumns: ["key", "updated_at"],
    canCreate: true,
    fields: [
      { key: "key", label: "Kulcs", type: "text", required: true },
      { key: "value", label: "Érték (JSON)", type: "json", required: true },
    ],
  },
  {
    key: "admin_bootstrap_emails",
    table: "admin_bootstrap_emails",
    title: "Admin e-mailek",
    description: "Regisztrációkor automatikusan admin szerepet kapó címek.",
    idKey: "email",
    group: "Beállítások",
    listColumns: ["email", "note"],
    canCreate: true,
    canDelete: true,
    fields: [
      { key: "email", label: "E-mail", type: "text", required: true },
      { key: "note", label: "Megjegyzés", type: "text" },
    ],
  },
];

export function getResource(key: string): ResourceDef | undefined {
  return ADMIN_RESOURCES.find((r) => r.key === key);
}
